### ISSUE TITLE
dependencies javax.security-api and soteria not found

### ISSUE THREAD

**Issue by lilian-benoit** [juneau001/JavaEE8-Playground#1]
Hi,

I have realize git clone and launch command "mvn package"

I have one error : 
[ERROR] Failed to execute goal on project AcmePools: Could not resolve dependencies for project org.javaee8recipes:AcmePools:war:2.0: The following artifacts could not be resolved: javax.security:javax.security-api:jar:1.0-m01, org.glassfish.soteria:soteria:jar:1.0-m01: Could not find artifact javax.security:javax.security-api:jar:1.0-m01

These artefacts are not present in maven central.
where can i found these artefacts ?

**Comment by juneau001** [comment]
Hi, and thanks for using the project.  Have you added the maven repositories at the bottom of the POM?  Specifically, ensure you have included the following repository, as I believe it houses the soteria dependencies.

```
<repository>
            <id>java.net-Public</id>
            <name>Maven Java Net Snapshots and Releases</name>
            <url>https://maven.java.net/content/groups/public/</url>
       
        </repository>
```

Thanks, and let me know if this doesn't work for you.

**Comment by juneau001** [comment]
I have updated the POM with the bintray repository which currently houses the Java EE Security dependencies.  I have also updated Lombok to 1.16.16.  Thanks for the feedback and let me know if there are any further issues.

**Comment by lilian-benoit** [comment]
It's okay for me. Thanks

**Comment by juneau001** [comment]
Glad to hear it, thanks for the update!
